# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 55fc5b2bf5945046a559b486793b66ef5fc518c6137b8194b7faa4d84fe0c5699e4717737d9200a4bd624dc08464390b3b91a88dec4b709103a0310e5fd35c65

test:
  secret_key_base: fede68d6270bf21aff27d7f64f587a4c3b46c2b37eb65c16f44411e38000fb7dd212449c970274090ce92f5c0df6f0d392d2c567eda8617173d72a9bc09128cb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
